import type { Campaign, Donation } from "./types"
import { PLACEHOLDER_IMAGES } from "./constants"

export const featuredCampaigns: Campaign[] = [
  {
    id: "1",
    title: "Help Ravi Fight Cancer",
    description:
      "Ravi, a 12-year-old boy from Mumbai, has been diagnosed with leukemia. His family needs financial support for his treatment.",
    image: PLACEHOLDER_IMAGES.cancer,
    targetAmount: 500000,
    amountRaised: 325000,
    donorsCount: 142,
    createdAt: "2023-12-15T10:00:00Z",
    updatedAt: "2024-04-20T15:30:00Z",
    status: "VERIFIED",
    type: "MEDICAL",
    organizerId: "user-1",
    organizer: {
      name: "Priya Sharma",
      image: PLACEHOLDER_IMAGES.ngo,
    },
    milestones: [
      {
        id: "m1",
        title: "Initial Diagnosis & Tests",
        description: "Cover the costs of initial diagnosis and medical tests",
        targetAmount: 100000,
        isCompleted: true,
        campaignId: "1",
      },
      {
        id: "m2",
        title: "First Phase of Treatment",
        description: "First round of chemotherapy and hospital stay",
        targetAmount: 200000,
        isCompleted: true,
        campaignId: "1",
      },
      {
        id: "m3",
        title: "Second Phase of Treatment",
        description: "Second round of treatment and medications",
        targetAmount: 200000,
        isCompleted: false,
        campaignId: "1",
      },
    ],
  },
  {
    id: "2",
    title: "Rebuild Shiva Temple After Earthquake",
    description:
      "The historic Shiva Temple in Uttarakhand was severely damaged in the recent earthquake. Help us rebuild this 500-year-old cultural heritage.",
    image: PLACEHOLDER_IMAGES.temple,
    targetAmount: 2000000,
    amountRaised: 750000,
    donorsCount: 320,
    createdAt: "2024-01-10T08:15:00Z",
    updatedAt: "2024-04-18T12:45:00Z",
    status: "VERIFIED",
    type: "RELIGIOUS",
    organizerId: "user-2",
    organizer: {
      name: "Temple Trust Committee",
      image: PLACEHOLDER_IMAGES.ngo,
    },
    milestones: [
      {
        id: "m4",
        title: "Structural Assessment",
        description: "Professional assessment of damage and rebuilding plan",
        targetAmount: 200000,
        isCompleted: true,
        campaignId: "2",
      },
      {
        id: "m5",
        title: "Foundation Repair",
        description: "Repair and strengthen the temple foundation",
        targetAmount: 800000,
        isCompleted: false,
        campaignId: "2",
      },
      {
        id: "m6",
        title: "Main Structure Rebuilding",
        description: "Rebuild the main temple structure with traditional materials",
        targetAmount: 1000000,
        isCompleted: false,
        campaignId: "2",
      },
    ],
  },
  {
    id: "3",
    title: "Education for 100 Rural Girls",
    description:
      "Support the education of 100 girls from rural villages in Bihar. This includes school fees, books, uniforms, and transportation for one year.",
    image: PLACEHOLDER_IMAGES.girlsEducation,
    targetAmount: 1000000,
    amountRaised: 850000,
    donorsCount: 275,
    createdAt: "2023-11-05T09:30:00Z",
    updatedAt: "2024-04-15T16:20:00Z",
    status: "VERIFIED",
    type: "EDUCATION",
    organizerId: "user-3",
    organizer: {
      name: "Education For All NGO",
      image: PLACEHOLDER_IMAGES.ngo,
    },
    milestones: [
      {
        id: "m7",
        title: "School Enrollment",
        description: "Enroll 100 girls in local schools and pay admission fees",
        targetAmount: 200000,
        isCompleted: true,
        campaignId: "3",
      },
      {
        id: "m8",
        title: "Books and Supplies",
        description: "Purchase textbooks, notebooks, and school supplies",
        targetAmount: 300000,
        isCompleted: true,
        campaignId: "3",
      },
      {
        id: "m9",
        title: "Uniforms and Transportation",
        description: "Provide uniforms and arrange transportation for students",
        targetAmount: 500000,
        isCompleted: false,
        campaignId: "3",
      },
    ],
  },
]

export const allCampaigns: Campaign[] = [
  ...featuredCampaigns,
  {
    id: "4",
    title: "Clean Water Project for Village",
    description:
      "Help us install water purification systems in 5 villages in Rajasthan where clean drinking water is scarce.",
    image: PLACEHOLDER_IMAGES.cleanWater,
    targetAmount: 800000,
    amountRaised: 320000,
    donorsCount: 98,
    createdAt: "2024-02-20T11:45:00Z",
    updatedAt: "2024-04-10T09:15:00Z",
    status: "OPEN",
    type: "NGO",
    organizerId: "user-4",
    organizer: {
      name: "Clean Water Initiative",
      image: PLACEHOLDER_IMAGES.ngo,
    },
    milestones: [
      {
        id: "m10",
        title: "Water Testing",
        description: "Test water quality in target villages",
        targetAmount: 100000,
        isCompleted: true,
        campaignId: "4",
      },
      {
        id: "m11",
        title: "Equipment Purchase",
        description: "Purchase water purification systems",
        targetAmount: 400000,
        isCompleted: false,
        campaignId: "4",
      },
      {
        id: "m12",
        title: "Installation and Training",
        description: "Install systems and train local operators",
        targetAmount: 300000,
        isCompleted: false,
        campaignId: "4",
      },
    ],
  },
  {
    id: "5",
    title: "Smart Classroom for Government School",
    description:
      "Transform a rural government school with digital learning tools including computers, projectors, and internet connectivity.",
    image: PLACEHOLDER_IMAGES.smartClassroom,
    targetAmount: 500000,
    amountRaised: 125000,
    donorsCount: 45,
    createdAt: "2024-03-05T14:20:00Z",
    updatedAt: "2024-04-12T10:30:00Z",
    status: "VERIFIED",
    type: "GOVERNMENT",
    organizerId: "user-5",
    organizer: {
      name: "Digital Education Foundation",
      image: PLACEHOLDER_IMAGES.ngo,
    },
    milestones: [
      {
        id: "m13",
        title: "Infrastructure Preparation",
        description: "Prepare classroom with electrical and network infrastructure",
        targetAmount: 100000,
        isCompleted: true,
        campaignId: "5",
      },
      {
        id: "m14",
        title: "Equipment Purchase",
        description: "Purchase computers, projector, and digital learning tools",
        targetAmount: 300000,
        isCompleted: false,
        campaignId: "5",
      },
      {
        id: "m15",
        title: "Teacher Training",
        description: "Train teachers on using digital tools for education",
        targetAmount: 100000,
        isCompleted: false,
        campaignId: "5",
      },
    ],
  },
  {
    id: "6",
    title: "Emergency Relief for Flood Victims",
    description: "Provide food, shelter, and medical aid to families affected by the recent floods in Kerala.",
    image: PLACEHOLDER_IMAGES.floodRelief,
    targetAmount: 1500000,
    amountRaised: 980000,
    donorsCount: 412,
    createdAt: "2024-03-15T08:00:00Z",
    updatedAt: "2024-04-19T17:45:00Z",
    status: "VERIFIED",
    type: "NGO",
    organizerId: "user-6",
    organizer: {
      name: "Disaster Relief Network",
      image: PLACEHOLDER_IMAGES.ngo,
    },
    milestones: [
      {
        id: "m16",
        title: "Immediate Food and Water",
        description: "Distribute food packets and drinking water to affected families",
        targetAmount: 500000,
        isCompleted: true,
        campaignId: "6",
      },
      {
        id: "m17",
        title: "Temporary Shelter",
        description: "Set up temporary shelters and provide basic necessities",
        targetAmount: 600000,
        isCompleted: true,
        campaignId: "6",
      },
      {
        id: "m18",
        title: "Medical Camps",
        description: "Organize medical camps and provide healthcare services",
        targetAmount: 400000,
        isCompleted: false,
        campaignId: "6",
      },
    ],
  },
]

export const userDonations: Donation[] = [
  {
    id: "d1",
    amount: 5000,
    createdAt: "2024-04-10T14:30:00Z",
    campaignId: "1",
    userId: "user-1",
    campaign: {
      title: "Help Ravi Fight Cancer",
      image: PLACEHOLDER_IMAGES.cancer,
    },
    transactionId: "txn_123456",
    status: "COMPLETED",
  },
  {
    id: "d2",
    amount: 2000,
    createdAt: "2024-03-25T09:15:00Z",
    campaignId: "3",
    userId: "user-1",
    campaign: {
      title: "Education for 100 Rural Girls",
      image: PLACEHOLDER_IMAGES.girlsEducation,
    },
    transactionId: "txn_789012",
    status: "COMPLETED",
  },
  {
    id: "d3",
    amount: 10000,
    createdAt: "2024-04-18T16:45:00Z",
    campaignId: "6",
    userId: "user-1",
    campaign: {
      title: "Emergency Relief for Flood Victims",
      image: PLACEHOLDER_IMAGES.floodRelief,
    },
    transactionId: "txn_345678",
    status: "COMPLETED",
  },
]

export const dashboardStats = {
  totalDonations: 3000,
  activeCampaigns: 3,
  communityImpact: 150,
  recentActivity: [
    {
      id: "1",
      type: "donation",
      amount: 1000,
      campaign: allCampaigns[0],
      date: "2024-03-15",
    },
    {
      id: "2",
      type: "campaign_created",
      campaign: allCampaigns[2],
      date: "2024-03-14",
    },
  ],
}

export const ngoCampaigns = [
  {
    id: "4",
    title: "Clean Water Initiative",
    description: "Providing clean drinking water to rural communities.",
    category: "ngo",
    image: PLACEHOLDER_IMAGES.cleanWater,
    targetAmount: 100000,
    raisedAmount: 40000,
    organizer: {
      name: "WaterAid NGO",
      image: PLACEHOLDER_IMAGES.ngo,
    },
    status: "active",
    endDate: "2024-12-31",
  },
  {
    id: "5",
    title: "Women Empowerment",
    description: "Supporting women entrepreneurs in rural areas.",
    category: "ngo",
    image: PLACEHOLDER_IMAGES.ngo,
    targetAmount: 75000,
    raisedAmount: 30000,
    organizer: {
      name: "WomenFirst NGO",
      image: PLACEHOLDER_IMAGES.ngo,
    },
    status: "active",
    endDate: "2024-12-31",
  },
]
